kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  name: master
  image: kindest/node:v1.19.11
- role: worker
  name: worker1
  image: kindest/node:v1.19.11
- role: worker
  name: worker2
  image: kindest/node:v1.19.11
featureGates:
  FeatureGateName: true
networking:
  # the default CNI will not be installed
  disableDefaultCNI: false
  kubeProxyMode: "ipvs"
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
