
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://127.0.0.1:9443/validate-ops-soer3n-info-v1alpha1-quarantine"
  failurePolicy: Fail
  name: vquarantine.kb.io
  rules:
  - apiGroups:
    - ops.soer3n.info
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - quarantines
  sideEffects: None
