---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-validation-webhook
  labels:
    component: incident-validation-webhook
spec:
  selector:
    matchLabels:
      app: incident-operator
      component: incident-validation-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: incident-operator
        component: incident-validation-webhook
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      serviceAccountName: iop
      securityContext:
        runAsUser: 65532
      containers:
      - image: hub.soer3n.info/library/incident-operator:0.0.2
        name: validation-webhook
        args:
          - "webhook"
          - "serve"
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs/
            name: webhook-tls
            readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: webhook-tls
          secret:
            secretName: incident-webhook
