apiVersion: ops.soer3n.info/v1alpha1
kind: Quarantine
metadata:
  name: quarantine-sample
spec:
  nodes:
  - name: worker1
    debugPod: false
    isolate: false
    rescale: false # if machine-controller is present
  resources:
  - type: daemonset
    name: ds-resource
  - type: deployment
    name: deployment-resource  
