apiVersion: ops.soer3n.info/v1alpha1
kind: Quarantine
metadata:
  name: quarantine-sample
spec:
  debug: false
  nodes:
  - name: mngt-mngt-pool-7c46bb775f-fghln
    isolate: false
    rescale: false # if machine-controller is present
  resources: []
  #- type: daemonset
  #  name: ds-resource
  #- type: deployment
  #  name: deployment-resource  
