apiVersion: ops.soer3n.info/v1alpha1
kind: Quarantine
metadata:
  name: quarantine-sample
spec:
  debug:
    enabled: true
    image: nicolaka/netshoot
  nodes:
  - name: node1
    isolate: true # add taint to node 
  - name: node3
    isolate: true # add taint to node 
  resources:
  - type: daemonset
    name: deployed-ds
    namespace: my-namespace
    keep: true
  #- type: deployment
  #  name: deployment-resource  
