apiVersion: ops.soer3n.info/v1alpha1
kind: Quarantine
metadata:
  name: quarantine-sample
spec:
  debug:
    enabled: true
    image: nicolaka/netshoot
  nodes:
  - name: mngt-mngt-pool-f47cdbdfc-r792b
    isolate: true # add taint to node 
    rescale: false # if machine-controller is present (not yet implemented)
  resources:
  - type: daemonset
    name: loki-stack-promtail
  #  namespace: loki-stack
  #- type: deployment
  #  name: deployment-resource  
