apiVersion: ops.soer3n.info/v1alpha1
kind: Quarantine
metadata:
  name: quarantine-sample
spec:
  debug:
    enabled: true
    image: nicolaka/netshoot
  nodes:
  - name: mngt-mngt-pool-f47cdbdfc-2mxtb
    isolate: true # add taint to node
  - name: mngt-mngt-pool-f47cdbdfc-r792b
    isolate: true # add taint to node
  resources:
  - type: daemonset
    name: loki-stack-promtail
    namespace: loki-stack
    keep: true
  #- type: deployment
  #  name: deployment-resource  
