apiVersion: ops.soer3n.info/v1alpha1
kind: Quarantine
metadata:
  name: quarantine-sample
spec:
  debug:
    enabled: true
    image: nicolaka/netshoot
  flags:
    disableEviction: false
    deleteEmptyDirData: true
    force: false
    ignoreErrors: false
  nodes:
  - name: mngt-mngt-pool-f47cdbdfc-5gmpq
    isolate: true # add taint to node
    flags:
      force: true
      ignoreAllDaemonSets: true
    resources:
    - type: deployment
      name: keycloak-operator
      namespace: keycloak
      keep: false
    - type: deployment
      name: kp-operator
      namespace: monitoring
      keep: true
  resources:
  - type: daemonset
    name: loki-stack-promtail
    namespace: loki-stack
    keep: true
  #- type: deployment
  #  name: deployment-resource  
