apiVersion: ops.soer3n.info/v1alpha1
kind: Quarantine
metadata:
  name: quarantine-sample
spec:
  debug:
    enabled: true
    image: nicolaka/netshoot
  nodes:
  - name: mngt-mngt-pool-f47cdbdfc-2mxtb
    isolate: true # add taint to node
  resources: []
