name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: build
      run: go build -v ./...

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: test packages
      run: go test -coverpkg ./internal/... ./tests/unit/...

  test-e2e-controllers:
    strategy:
      fail-fast: false
      matrix:
        version:
        - v1.24.1
        - v1.23.6
        - v1.22.9
        - v1.21.12
        - v1.20.15
    runs-on: ubuntu-latest
    name: test-e2e-controllers-${{ matrix.version }}
    needs:
    - build
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: create k8s Kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        node_image: kindest/node:${{ matrix.version }}
        cluster_name: dev-cluster
        config: .github/kind.yaml
    - name: test controllers
      run: go test -coverpkg ./controllers/... ./tests/e2e/controller/...

  test-e2e-webhooks:
    runs-on: ubuntu-latest
    name: test-e2e-webhooks
    needs:
    - build
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: install binaries for testing
      run: make test-setup
    - name: test controllers
      run: go test -coverpkg ./webhooks/... ./tests/e2e/webhook/...
