name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: build
      run: go build -v ./...

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: test packages
      run: go test -coverpkg ./internal/... ./tests/unit/...

  test-k8s:
    strategy:
      fail-fast: false
      matrix:
        version:
        - v1.21.1
        - v1.20.7
        - v1.19.11
    runs-on: ubuntu-latest
    name: test-e2e-k8s-${{ matrix.version }}
    needs:
    - build
    steps:
    - uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: create k8s Kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        node_image: kindest/node:${{ matrix.version }}
        cluster_name: dev-cluster
        config: .github/kind.yaml
    - name: test controllers
      run: ACK_GINKGO_DEPRECATIONS=1.16.4 go test -coverpkg ./controllers/... ./tests/e2e/...
