name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: build
      run: go build -v ./...

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: test packages
      run: go test -coverpkg ./internal/... ./tests/unit/...

  test-e2e-controllers:
    runs-on: ubuntu-latest
    name: test-e2e-controllers
    needs:
    - build
    steps:
    - uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: create k8s Kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        node_image: kindest/node:${{ matrix.version }}
        cluster_name: dev-cluster
        config: .github/kind.yaml
    - name: test controllers
      run: ACK_GINKGO_DEPRECATIONS=1.16.4 go test -coverpkg ./controllers/... ./tests/e2e/controller/...

  test-e2e-webhooks:
    runs-on: ubuntu-latest
    name: test-e2e-webhooks
    needs:
    - build
    steps:
    - uses: actions/checkout@v2
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: install binaries for testing
      run: make test-setup
    - name: test controllers
      run: ACK_GINKGO_DEPRECATIONS=1.16.4 go test -coverpkg ./api/... ./tests/e2e/webhook/...
